/* Generated By:JJTree: Do not edit this line. ASTGroupByClause.java */

package uff.dew.svp.javaccparser;

public class ASTGroupByClause extends SimpleNode {
  public ASTGroupByClause(int id) {
    super(id);
  }

  public ASTGroupByClause(XQueryParser p, int id) {
    super(p, id);
  }

}
