/* Generated By:JJTree: Do not edit this line. ASTSimplePathExpr2.java */

package uff.dew.svp.javaccparser;

public class ASTSimplePathExpr2 extends SimpleNode {
  public ASTSimplePathExpr2(int id) {
    super(id);
  }

  public ASTSimplePathExpr2(XQueryParser p, int id) {
    super(p, id);
  }

}
