/* Generated By:JJTree: Do not edit this line. XQueryParserTreeConstants.java */

package uff.dew.svp.javaccparser;

public interface XQueryParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTELMTCONSTRUCTOR = 1;
  public int JJTELMTCONTENT = 2;
  public int JJTENDTAG = 3;
  public int JJTATTLIST = 4;
  public int JJTATTRIBUTEVALUEPAIR = 5;
  public int JJTATTVALUE = 6;
  public int JJTATTVALUECONTENT = 7;
  public int JJTPATHEXPR = 8;
  public int JJTSIMPLEPATHEXPR = 9;
  public int JJTSIMPLEPATHEXPR2 = 10;
  public int JJTVARNAME = 11;
  public int JJTENCLOSEDEXPR = 12;
  public int JJTFUNCTIONEXPR = 13;
  public int JJTFUNCCOUNT = 14;
  public int JJTFUNCMAX = 15;
  public int JJTFUNCMIN = 16;
  public int JJTFUNCSUM = 17;
  public int JJTFUNCAVERAGE = 18;
  public int JJTFLWOREXPR = 19;
  public int JJTFORCLAUSE = 20;
  public int JJTLETCLAUSE = 21;
  public int JJTDOCUMENTEXPR = 22;
  public int JJTWHERECLAUSE = 23;
  public int JJTGROUPBYCLAUSE = 24;
  public int JJTORDERBYCLAUSE = 25;
  public int JJTORDERSPECLIST = 26;
  public int JJTORDERSPEC = 27;
  public int JJTORDERASCENDING = 28;
  public int JJTORDERDESCENDING = 29;
  public int JJTRETURN = 30;
  public int JJTEXPR = 31;
  public int JJTOREXPR = 32;
  public int JJTANDEXPR = 33;
  public int JJTCOMPARISONEXPR = 34;
  public int JJTVALUEEXPR = 35;
  public int JJTGENERALCOMP = 36;
  public int JJTEQUALS = 37;
  public int JJTLESSTHAN = 38;
  public int JJTLESSTHANEQUALS = 39;
  public int JJTGREATERTHAN = 40;
  public int JJTGREATERTHANEQUALS = 41;
  public int JJTNOTEQUALS = 42;
  public int JJTPRIMARYEXPR = 43;
  public int JJTLITERAL = 44;
  public int JJTNUMERICALLITERAL = 45;
  public int JJTPARENTHESIZEDEXPR = 46;
  public int JJTUNIONEXPR = 47;
  public int JJTQNAME = 48;
  public int JJTSLASH = 49;
  public int JJTDOUBLESLASH = 50;
  public int JJTINTEGERLITERAL = 51;
  public int JJTDECIMALLITERAL = 52;
  public int JJTDOUBLELITERAL = 53;
  public int JJTSTRINGLITERAL = 54;


  public String[] jjtNodeName = {
    "Start",
    "ElmtConstructor",
    "ElmtContent",
    "EndTag",
    "AttList",
    "AttributeValuePair",
    "AttValue",
    "AttValueContent",
    "PathExpr",
    "SimplePathExpr",
    "SimplePathExpr2",
    "VarName",
    "EnclosedExpr",
    "FunctionExpr",
    "FuncCount",
    "FuncMax",
    "FuncMin",
    "FuncSum",
    "FuncAverage",
    "FLWORExpr",
    "ForClause",
    "LetClause",
    "DocumentExpr",
    "WhereClause",
    "GroupByClause",
    "OrderByClause",
    "OrderSpecList",
    "OrderSpec",
    "OrderAscending",
    "OrderDescending",
    "Return",
    "Expr",
    "OrExpr",
    "AndExpr",
    "ComparisonExpr",
    "ValueExpr",
    "GeneralComp",
    "Equals",
    "LessThan",
    "LessThanEquals",
    "GreaterThan",
    "GreaterThanEquals",
    "NotEquals",
    "PrimaryExpr",
    "Literal",
    "NumericalLiteral",
    "ParenthesizedExpr",
    "UnionExpr",
    "QName",
    "Slash",
    "DoubleSlash",
    "IntegerLiteral",
    "DecimalLiteral",
    "DoubleLiteral",
    "StringLiteral",
  };
}
